services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./volumes/gitea/data:/data
    healthcheck: 
      test: curl -f http://localhost:3000/api/v1/version || exit 1
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.${DOMAIN}`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
      - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22
