services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./volumes/home-assistant:/config
    privileged: true
    healthcheck: 
      test: curl -f http://localhost:8123 || exit 1
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-assistant.rule=Host(`home-assistant.${DOMAIN}`)
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123
