services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/home-assistant:/config
    privileged: true
    networks:
      traefik:
        ipv4_address: 172.21.0.10
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-assistant.rule=Host(`home-assistant.${DOMAIN}`)
      - traefik.http.routers.home-assistant.entrypoints=web
      # - traefik.http.routers.home-assistant.tls.certresolver=letsencrypt
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123
