services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ./volumes/home-assistant:/config
      - /var/run/docker.sock:/var/run/docker.sock
    # privileged: true
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_b464b0276531ef1187ba57cfdfbc56eb-if00-port0:/dev/zigbee
    healthcheck:
      test: curl -f http://localhost:8123 || exit 1
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.home-assistant.rule: Host(`home-assistant.${DOMAIN}`)
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123
