services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.129.0
    volumes:
      - ./volumes/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ}
      DB_HOSTNAME: immich-database
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_PASSWORD_FILE: /run/secrets/IMMICH_DB_PASS
      REDIS_HOSTNAME: immich-redis
    secrets:
      - IMMICH_DB_PASS
    depends_on:
      - immich-redis
      - immich-database
    restart: unless-stopped
    networks:
      traefik:
      immich:
    labels:
      traefik.enable: true
      traefik.http.routers.immich.rule: Host(`immich.${DOMAIN}`)
      traefik.http.services.immich.loadbalancer.server.port: 2283

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.126.1
    environment:
      TZ: ${TZ}
      DB_HOSTNAME: immich-database
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_PASSWORD_FILE: /run/secrets/IMMICH_DB_PASS
      REDIS_HOSTNAME: immich-redis
    secrets:
      - IMMICH_DB_PASS
    volumes:
      - immich-model-cache:/cache
    restart: unless-stopped
    networks:
      immich:

  immich-redis:
    container_name: immich-redis
    image: docker.io/library/redis:7
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      immich:

  immich-database:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/IMMICH_DB_PASS
      POSTGRES_INITDB_ARGS: "--data-checksums"
    secrets:
      - IMMICH_DB_PASS
    volumes:
      - ./volumes/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped
    networks:
      immich:

volumes:
  immich-model-cache:

networks:
  immich:

secrets:
  IMMICH_DB_PASS:
    file: env/.immich_db_pass
