services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${UID}:${GID}
    restart: unless-stopped
    volumes:
      - ./volumes/jellyfin/config/jellyfin:/config
      - ./volumes/jellyfin/films:/films
      - ./volumes/jellyfin/shows:/shows
      - ./volumes/jellyfin/music:/music
      - ./volumes/jellyfin/other:/other
    environment:
      TZ: ${TZ}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.${DOMAIN}`)
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
