services:
  linkwarden-db:
    image: postgres:16-alpine
    container_name: linkwarden-db
    env_file: ./env/linkwarden.env
    restart: unless-stopped
    volumes:
      - ./volumes/linkwarden/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
    networks:
      linkwarden:

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    env_file: ./env/linkwarden.env
    restart: unless-stopped
    volumes:
      - ./volumes/linkwarden/data:/data/data
    healthcheck:
      test: curl -f http://localhost:3000/api/v1/logins || exit 1
    depends_on:
      - linkwarden-db
    networks:
      traefik:
      linkwarden:
    labels:
      traefik.enable: true
      traefik.http.routers.linkwarden.rule: Host(`linkwarden.${DOMAIN}`)
      traefik.http.services.linkwarden.loadbalancer.server.port: 3000

networks:
  linkwarden:
