services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    volumes:
      - ./volumes/mealie:/app/data
    environment:
      # enable for first account
      # ALLOW_SIGNUP: "true"
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      BASE_URL: https://mealie.${DOMAIN}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.mealie.rule: Host(`mealie.${DOMAIN}`)
      traefik.http.services.mealie.loadbalancer.server.port: 9000
