services:
  owncloud:
    image: owncloud/ocis:latest
    container_name: owncloud
    restart: unless-stopped
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      TZ: ${TZ}
      OCIS_URL: https://owncloud.${DOMAIN}
      OCIS_INSECURE: false
      PROXY_TLS: false
      PROXY_ENABLE_BASIC_AUTH: true
    volumes:
      - ./volumes/owncloud/config:/etc/ocis
      - ./volumes/owncloud/data:/var/lib/ocis
    healthcheck:
      test: curl -f http://localhost:9104/healthz || exit 1
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.owncloud.rule: Host(`owncloud.${DOMAIN}`)
      traefik.http.services.owncloud.loadbalancer.server.port: 9200
