services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      FTLCONF_dns_listeningMode: all
      PIHOLE_UID: ${UID}
      PIHOLE_GID: ${GID}
    env_file:
      - ./env/pihole.env
    volumes:
      - ./volumes/pihole:/etc/pihole
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.rule: Host(`pihole.${DOMAIN}`) || Host(`${LOCALIP}`)
      traefik.http.services.pihole.loadbalancer.server.port: 80
