services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      WATCHTOWER_CLEANUP: true
    env_file: ./env/watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
